### ISSUE TITLE
Assistance -- Getting Image URL's.

### ISSUE THREAD

**Issue by Anaximander-Thales** [ShaneCullinane/discogs#2]
I was working on getting the image url's for artist and albums and noticed that that information wasn't populated despite the fact that I had provided my discogs personal token.

It appeared that the token wasn't being appended properly for artist information (artist/artist releases).  I was able to get it when I did an artist find by adding `$this->addToken()` in Resource.php in funtion find.
```php
    /**
     * Set the identifer for the requested resource e.g. a release or artist id, a search string
     * Returns an instance of the relevant Resource child class
     *
     * @param mixed $identifier
     * @return $this
     */
    public function find($identifier) {

        if (empty ($this->identifier)) {
            $this->identifier = $identifier;
            $this->addToken();
            $this->url .= "/$identifier";
        }
        return $this;

    }
```

If I'm mistaken that this is appropriate please let me know.

As I'm a novice, I won't attempt to do a pull request, make the update and then push it up for review (if I have the terms correct).  I'll investigate how to do it in the future so if I need to I'll be able to do it.

Thanks,
AT

**Comment by Anaximander-Thales** [comment]
Spoke to soon -- didn't test it.  Adding in the add token actually ends up removing all the other information except the images.

I've tried adding in just an images function similar to the find function (made sure to add to Resource Interface), but I'm not intelligent enough to implement it yet.  Currently getting an undefined method, but I can't find any other location to add a place holder.

**Comment by ShaneCullinane** [comment]
You can get the images for releases if you modify the file src/Resources/Release.php so that it looks like this:

    class Release extends Resource{

        protected $resource = 'releases/{release_id}';

        public function find($releaseId) {

            $this->identifier = $releaseId;
            $this->url = str_replace('{release_id}', $releaseId, $this->url);
            $this->addToken();
            return $this;
        }

    }

At least it worked for me during one quick test. I think there was some reason not to use addToken() all the time which is why some of the shanecullinane\Discogs\Resources files override that method as the change above does for Release.php. I forget what the reason is now. 

This was a learning exercise for me too, I'm pleasantly surprised and encouraged to find someone using it! I'll try and do a bit more on it, but I have hardly any time these days...

**Comment by Anaximander-Thales** [comment]
I completely understand.  The release images are showing up.  I tried a similar option for artist, and this:

```php
// Using discogs api -- establish search
$searchArtists = new Discogs('Artist');
// search for the artist
$results = $searchArtists->find($artistID);

// grab results
$artist = $results->get();

// Grab the artist releases
$releases = $results->releases()->perPage($ppc)->get();
```
$releases and $artist are the same output.


Grr -- I wish I could get PHPStorm and xdebug worked out so that I could help out.  It would seem the nicest solution would be to have an images function that could retrieve the artist, release or masterrelease images.

Regardless, Thank you for your time.

**Comment by ShaneCullinane** [comment]
The token is now added to every request to discogs, since adding it doesn't seem to cause any trouble where it's not needed. SO photos should be included. In  case you're still interested it's in  the getResponse() method of Resource.php...
