### ISSUE TITLE
Search restricted to a type

### ISSUE THREAD

**Issue by jpmurray** [ShaneCullinane/discogs#3]
As per Discogs documentations, when searching, we can restrict the search to specific type: "release, master, artist, label".

Is there a way to specify it?

**Comment by ShaneCullinane** [comment]
Hi. This seems to work : 

    $discogs 				= new Discogs('Search');
    $search 				= $discogs->find('search term');
    $results 				= $search->addParam('label', 'label name')->get();

**Comment by jpmurray** [comment]
Well, it works flawlesly!

I was looking too far away I guess, I was already preparing a pull request modifying the code so I could do a find("search", "type") ;-)
